modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "${modGitHubUrl}/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
displayURL = "https://faststats.dev/mods"
authors = "MarcPG, David, NonSwag"
description = """
${modDescription}
"""

bannerFile = "faststats.png"
iconFile = "faststats.png"
iconBlur = true
logoFile = "faststats.png"
logoBlur = true

[[dependencies.${modId}]]
modId = "minecraft"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"
